### ISSUE TITLE
[misic] do not use /tmp as the TMPDIR

### ISSUE THREAD

**Issue by ildar** [manilarome/awesome-glorious-widgets#2]
this is illegal. Use $TMPDIR instead.

**Comment by eromatiya** [comment]
Oh. What is the best temp directory, though? My $TMPDIR doesn't have a value.

**Comment by ildar** [comment]
On Mon, Mar 2, 2020 at 1:24 PM Gerome Matilla wrote:

> Oh. What is the best temp directory, though? My $TMPDIR doesn't have a
> value.
>
Oh! I'm sorry for the confusion.
Using common /tmp for all users is considered a bad security practice.
Hence TMPDIR (https://en.wikipedia.org/wiki/TMPDIR) may be different from
/tmp and should have precedence over mere /tmp.
For me, it's just spoiling /tmp with constant updating&recreating.
Thanks.

**Comment by eromatiya** [comment]
Thanks for the info. So what's the alternative for `/tmp` and `/var/tmp`? `$HOME/.cache/` or something?

**Comment by ildar** [comment]
The true way :-) is to honor $TMPDIR and $TMP over blind /tmp.
In my case TMPDIR is /tmp/.private/$USER which is true in ALTLinux and Owl.

**Comment by eromatiya** [comment]
Ah, so first create a directory in `/tmp` using `mkdir -p /tmp/.private/$USER`. Then, `chmod 700 /tmp/.private/$USER` that folder to make it accessible only for the $USER? Is that right?

**Comment by ildar** [comment]
No. Sorry. This setting is distro-specific.
I'd suggest following:
1. If $TMPDIR or $TMP is set, then use it instead `/tmp`
2. replace `/tmp/cover.jpg` with `$TMPDIR/$SOMEDIR/cover.jpg` where
$SOMEDIR is something `mktemp`-related or kinda
`$TMPDIR/mpd-stuff/cover.jpg`.
Thanks!

**Comment by eromatiya** [comment]
Understood! I'll try to implement your suggestion! Thanks!

**Comment by eromatiya** [comment]
Hello, I already implemented this in my [repo](https://github.com/manilarome/Glorious-Dotfiles). Although, it's only implemented in the `Floppy` setup because I will be rewriting the other setups.

**Comment by ildar** [comment]
thanks. Though I see similar fix should be applied to other parts:
https://github.com/manilarome/the-glorious-dotfiles/search?q=tmp&unscoped_q=tmp
At least background changing creates folder in /tmp.

**Comment by eromatiya** [comment]
Thanks for the suggestion, but I'm sorry I will not be changing those files. Those files are only configs and scripts and it's my "personal dotfiles".  I feel that every user is obligated to check the code of every configs/scripts that he/she will use/run. So I will let the user change it for himself/herself. Thanks again! :)
